### ISSUE TITLE
Normalise YAGO to DBPedia?

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#2] opened 2014-06-18 10:17 UTC
For the town 'Franeker' a YAGO URI was used to identify it. YAGO has owl:sameAs to DBPedia so we could normalise YAGO URIs to DBPedia ones?

**Comment by kliegr** [comment] 2014-06-18 15:46
THD provides both DBpedia (http://dbpedia.org/resource/Franeker) and YAGO URI. Can you doublecheck that the DBpedia URI is not also listed in the results?

**Comment by rtroncy** [comment] 2014-08-05 08:16
@lyndonnixon Can you please follow-up on this? We need more information to trace the problem, give us the annotation where this entity is used, etc.

**Comment by lyndonnixon** [comment] 2014-08-05 12:27
@kliegr @rtroncy  I am looking at the automated results for http://www.linkedtv.eu/wiki/index.php/Scenario_realisation_final#TKK_Example 
Follow the link under Annotation "Automated results sparql results"
You will see 3 YAGO URLs (Hessel and 2 x Franeker), no DBPedia equivalent

**Comment by rtroncy** [comment] 2014-08-05 13:26
Hum, this is weird, since as you can see at http://nerd.eurecom.fr/annotation/1508533, THD correctly disambiguates "Franeker" with http://nl.dbpedia.org/resource/Franeker.

@jthomsen can you tell us when TV2RDF has been launched for the last time for the media resource http://data.linkedtv.eu/mediaresource/8a8187f2-3fc8-cb54-0140-7dccd76f0001 ? And whether this is the _good_ media resource to use for the AVRO use case?
Tagging @jluisred for reference as well

**Comment by jthomsen** [comment] 2014-08-05 14:19
the last time TV2RDF has been launched on http://api.linkedtv.eu/mediaresource/8a8187f2-3fc8-cb54-0140-7dccd76f0001/ was 2014/06/25

whether this is the _good_ media resource for AVRO I don't know; I actually don't know which one they choose

**Comment by rtroncy** [comment] 2014-08-05 14:33
Is it not the role of the platform to know this information? It cannot really be the content providers. The one who is creating a new media resource UUID when there is a need for re-processing analysis / annotation / enrichment is the platform.

**Comment by jthomsen** [comment] 2014-08-05 14:41
ok, seems to have misunderstood what you meant by _good_ - on behalf of the platform this UUID is _good_ in the sense that it includes the most recent results available for this media resource

**Comment by rtroncy** [comment] 2014-08-05 14:45
@jluisred Can you look at why TV2RDF launched on the subtitles attached to http://data.linkedtv.eu/mediaresource/8a8187f2-3fc8-cb54-0140-7dccd76f0001 provides different results than NERD launched on a small excerpt (see above)?

**Comment by jthomsen** [comment] 2014-08-05 14:50
related files can be found in http://api.linkedtv.eu/mediaresource/8a8187f2-3fc8-cb54-0140-7dccd76f0001

**Comment by jluisred** [comment] 2014-08-05 16:04
Hello

Apparently the problem is not in TV2RDF but somewhere else...

If you take a look at the [RDF generated](http://linkedtv.eurecom.fr/tv2rdf/api/mediaresource/8a8187f2-3fc8-cb54-0140-7dccd76f0001/serialization?metadataType=subtitle) for that MediaResource in the TV2RDF service regarding the entity Franeker:
- The disambiguation URL ( http://yago-knowledge.org/resource/Franeker ) does not appear at all.
- Instead, you'll find 4 entities (http://data.linkedtv.eu/entity/d57cb0d0-ea15-444b-9da0-6da951062349, http://data.linkedtv.eu/entity/12804c3d-2e80-4cef-a007-7a1d6273de0f, http://data.linkedtv.eu/entity/876d12e9-0750-4c83-97aa-5737dbb9ecb9, http://data.linkedtv.eu/entity/2e3aabec-59a0-4da3-9ac0-c054c9c5464a) with disambiguation URLs http://dbpedia.org/resource/Franeker and http://de.dbpedia.org/resource/Franeker

So why they aren't include on the results? Well, if you search for any of the 4 entities in the LinkedTV triple store (e.g, via describe (http://data.linkedtv.eu/entity/12804c3d-2e80-4cef-a007-7a1d6273de0f), they simply don't exist, see the results of this [SPARQL query](http://data.linkedtv.eu/sparql?default-graph-uri=&query=describe+%28%3Chttp%3A%2F%2Fdata.linkedtv.eu%2Fentity%2F12804c3d-2e80-4cef-a007-7a1d6273de0f%3E%29&should-sponge=&timeout=0&debug=on)

So it seems to me that even if the TV2RDF process is finished:
1) New results have not been properly ingested into the platform
2) Old results have not been properly flushed, and this is why those Yago links keep appearing

**Comment by jthomsen** [comment] 2014-08-05 16:09
Hi @joseluis, thanks for checking! so it seems I have to check with @alisarioglu what possibly went wrong here (unfortunately he is on holidays right now)

**Comment by rtroncy** [comment] 2014-08-05 16:27
Thanks @jluisred for this thorough investigation.

@jthomsen There are more and more urgent issues that have to be dealt with! What is the ETA for this one?

**Comment by jthomsen** [comment] 2014-08-05 21:33
well, I will check this asap; in the worst case I'll have to leave it to @alisarioglu directly after his return; i.e. in that case ETA would be end of August

**Comment by rtroncy** [comment] 2014-08-20 10:19
Closing this issue since it is solved with the new install of Virtuoso and clean refresh of the data

**Closed as completed by rtroncy** 2014-08-20 10:19 UTC
