### ISSUE TITLE
UEP: check and possibly change crawling approach to specific White List sites

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#11] opened 2014-07-21 13:16 UTC
Testing with AVRO.nl. see http://www.linkedtv.eu/wiki/index.php/Enrichment_types_in_TKK#Broadcasters_archive
The useful media enrichments on this site need to be extracted from the Player pages (video link or HTML link + associated metadata for linking to entities)

**Comment by kliegr** [comment] 2014-07-28 12:08
I believe this is  the same issue as "there is a total of ONE video coming from RBBs White List." reported on the mailing list.

It seems that the culprit is not the indexing but retrieval. The recommender query formulation for MediaCollector seems to be overly restrictive, yielding very low recall. We are looking how to fix this problem, probably by introducing adaptive querying layer as proposed by José Luis, which will broaden the query with additional fields if the number of results is small or zero.

**Comment by lyndonnixon** [comment] 2014-08-01 15:46
Dashboard tells me you indexed 4 557 webpages at avro.nl and have indexed 717 videos. I assume this is subsumptive, i.e. the videos are all on webpages which are indexed, What is not clear is if other webpages had video you didnt index because you couldnt get a video URL for example - IMHO if you know a page contains video you could index it as video but provide only a micropostUrl and no mediaUrl. As enrichment, the player would direct the user to the webpage rather than the video alone. 
All the pages at avro.nl/_/player/_/ seem to be individually embedded media and thus could be crawled as such, indexing each page as audio/video and grabbing the title and description text which seems to be in the same structure on every page.

**Comment by kliegr** [comment] 2014-08-04 08:41
There are two possible problems. First, the crawler does index videos at avro.nl/*/player. There are 557 videos indexed. However, our AvroNLExtractor seems to fail correctly identify the title for the video, which results in these videos not being retrieved in response to a query. This might have been caused by an update to the Avro website.
 As to the count of the indexed videos, there are at least two formats in which  they are present (http://avro.nl/tussenkunstenkitsch/player/8210427/ and http://avro.nl/tussenkunstenkitsch/player/AVRO_1655975/).

**Comment by lyndonnixon** [comment] 2014-08-04 12:37
(Tomas, email, 4 August)
We have developed several prototypical extractors for media items for
the most important whitelist sites. RBB Online, SWR and AVRO are among
those. However, when the website layout  changes, we need to adapt the
extractor.
This seems to be actually the reason for this bug
https://github.com/linkedtv/wp2/issues/11

**Comment by lyndonnixon** [comment] 2014-08-04 12:38
As you point out, in some cases the crawler is not associating title and description text with the media object. In others, I wonder if the lack of an extractable media link is
causing the website to be indexed but not the image/video as image/video (as I suggested, enrichment could point to a media file when it can but also fall back to a link to a HTML page with embedded media when necessary). Finally, I wonder if some sites have not been fully crawled (the amount of webpages often seems much lower than the amount of embedded media the Mediathek likely has).
Can you please comment on plans to correct these points and the timeline for implementation? I feel we need to define also some means to evaluate the UEP crawling to know if/when it seems to have indexed enough white list content (to find several matches for typical entities in the scenarios).  This is a critical task if we are to offer useful automated results from the LinkedTV Platform to the editors.

**Comment by kliegr** [comment] 2014-08-04 12:48
The most aggressive timeline is to fine tune and update the
extractors for the top white-listed sites  by the end of  September,
and have an updated index in the October. (more in email)

**Comment by rtroncy** [comment] 2014-08-05 15:25
This "aggresive timeline" has been revised in today's WP2 Telecon, see also the minutes at http://www.linkedtv.eu/wiki/index.php/WP2/Telecon_05-08-14

**Comment by lyndonnixon** [comment] 2014-08-18 09:23
@rtroncy can you please add the precise timeline into this thread for ease of reference?
@kliegr sent my comments per mail on the revised avro.nl crawl, improved but not perfect:
- Crawl video from the other programme sections, like Presentatoren, Zoeken, Kunstuurmuseumgasten (since this is arguably more interesting than crosslinking to other TKK content)(ask Lotte for a list)
- Extract correctly title and description, currently plainText contains a concatenation of all extracted text from the HTML! This is useless for player display. The title is only (from the above example) 'Japans kaststel & twee houten sculptuurtjes' and description 'Vanuit diverse musea bespreken Nelleke van der Krogt en haar team weer verrassende kitsch en veelzijdige kunst! Woensdag 16 april om 20:30 uur op Nederland 1.' These are EXPLICITLY given in the HTML metadata!!! og:title and og:description

**Comment by rtroncy** [comment] 2014-08-19 10:56
IRAPI udpate timeline, as reported by @kliegr:
- Focused crawler update for parts of avro.nl (wraps on-site video search of selected white-listed websites) ... 25/08
- Fix bug when encountering the string ".avi" in web pages wrongly indicating that there is a video to crawl ... 25/08
- Favor precision over recall in the indexing strategy ... 25/08
- Add a "relevance = value" field in the new result of the Unstructured Search Module ... 25/08/2014 
- New release of IRAPI ... mid-September (unclear what this new release will contain over the 25/08 milestone, the duplicate results issue #4?)

**Comment by lyndonnixon** [comment] 2014-10-08 10:35
Hi, intermediate testing for images crawled from Museum Martena site (http://ir.lmcloud.vse.cz/irapi/media-server/?q=source_webpage_url:%22museummartena.nl%22&media_type=image&row=100000&thd=yes) returns first non-working URLs e.g. http://www.museummartena.nl/images/museummartena.jpg

**Comment by rtroncy** [comment] 2014-10-08 11:45
Indeed, from the micropost URL, the image is at http://www.museummartena.nl/themes/museummartena/images/museummartena.jpg and not http://www.museummartena.nl/images/museummartena.jpg. A bug in your crawler @kliegr ?

**Comment by kliegr** [comment] 2014-10-08 12:17
The website simply changed the location of the image and the Nutch has not yet rediscovered that the picture is gone. It may of course  be that it has not been removed due to a bug. We plan to do a review of the cleanup process.

**Comment by rtroncy** [comment] 2014-11-09 12:45
@kliegr Do you have any update regarding this bug?

**Comment by cervebar** [comment] 2014-11-10 17:25
the cleanup of irapi webpage index has finished. Now we are performing the
cleanup of the media indexes. Given the large number of objects indexed and
the corresponding volume of HTTP request, this is estimated to take 10-14
days. Once the cleanup has finished, this should resolve github issues #4,
#11.

**Comment by lyndonnixon** [comment] 2014-11-12 11:53
The AVRO TKK webpage seems to have been relaunched with a different layout for the player pages
e,g, http://web.avrotros.nl/tussenkunstenkitsch/player/POMS_AVRO_677869/

WIll this affect IRAPI results for the TKK scenario?

**Comment by rtroncy** [comment] 2014-12-02 15:01
@cervebar Tracking down this issue, can we close it? Is the cleanup of the irapi webpage index finished? Can you provide evidences for this?

**Comment by cervebar** [comment] 2014-12-03 08:08
@rtroncy 
Cleanup removes aproximately
video: 8000 from 55000 
image: 250 000 from 1 400 000
podcast: 8000 from 25000
As I wrote in my previous email,
<i>
Unfortunately it doesn't mean, that these not valid urls(media or webpage) can't be there again, because the index is in constant crawling progress.
 In this time we are working on continuous cleaning process, so these inconvenience should be minimized.</i>

I suggest to close this issue, after new release of our system with automatic cleanup, which should be at the end of this week or at the beginning of the next one.

One option to consider is to include check to IRAPI at query time, but it can slow response.

**Comment by rtroncy** [comment] 2014-12-03 09:03
I'm happy to close this issue if I see evidences that the bug is fixed, i.e. if you show me you have done significant tests that demonstrate that this issue is resolved minus the caveat you mentioned.

In the current state, simple tests I'm doing seem to fail :-(
Examples:
- http://ir.lmcloud.vse.cz/irapi/media-server/?q=source_webpage_url:%22museummartena.nl%22&media_type=video&row=100000&thd=yes returns only 1 result from boutique.arte.tv !!! Why? Your dashboard at http://ir.lmcloud.vse.cz/irDashboardMaven-1.0/ says that this source has 0 video in its index.
- http://ir.lmcloud.vse.cz/irapi/media-server/?q=source_webpage_url:%22ard.de%22&media_type=video&row=100000&thd=yes returns only 3 responses while your dashboard says there is 21 videos !
  And I could go on ... what am I doing wrong?

**Comment by cervebar** [comment] 2014-12-03 09:34
@rtroncy 
1)
The queries are in wrong format, the IRAPI has changed according to requirements (2 months ago).
There is no more support for this type of query. For better understanding IRAPI works more like a Google search, but over a smaller set of webpages.

full documentation is here: http://www.linkedtv.eu/wiki/index.php/UEP_unstructured_search_module
example query: 
http://ir.lmcloud.vse.cz/irapi/media-server/?q=%22Nelleke%20van%20der%20Krogt%22&media_type=video&row=1&domain_source=SV

2)
Thanks for noticing <i><b>boutique.arte.tv</b></i> - this was crawled as outlink from avro.nl, so we should link it to avro.nl or add new line for this host in  a Dashboard.

3)
Functionality that, you wanted to achieve with your queries, can be added, if you want it.

**Comment by rtroncy** [comment] 2014-12-03 11:06
I just picked up queries written earlier in this thread. Indeed, IRAPI has changed substantially over the last months. Are you saying I cannot search for videos on a particular source site? Can you use joker (e.g. '*') in my search term query?

boutique.arte.tv should be a new line (this is a new host) and there is clearly no reason why it is linked to museummartena.nl !

Again, before closing this issue, I want to see extensive testing that this is resolved. Please, provide me evidences of such an extensive testing.

**Comment by cervebar** [comment] 2014-12-03 11:23
<i>I just picked up queries written earlier in this thread. Indeed, IRAPI has changed substantially over the last months. Are you saying I cannot search for videos on a particular source site? Can you use joker (e.g. '*') in my search term query?</i>
Jokers are not allowed, query is reinterpreted by IRAPI (recognizes if it comes as a phrase query, term query or one term) and there is a cascade of queries over different precision fields now.

<i>
boutique.arte.tv should be a new line (this is a new host) and there is clearly no reason why it is linked to museummartena.nl !</i>
Just to be clear it is not linked to museummartena.nl, it is just linked  to nowhere. I will fix it.
<i>
Again, before closing this issue, I want to see extensive testing that this is resolved. Please, provide me evidences of such an extensive testing.</i>
Ok, that's fair requirement for closing.

**Comment by rtroncy** [comment] 2014-12-03 12:18
OK. Thanks for the clarification. Let us know what's your schedule and plans for this testing then.

**Comment by cervebar** [comment] 2014-12-08 11:55
@rtroncy 

<ul>
<li>
I have deployed Cleanup job, that runs weekly on all data, if webpage status is GONE then it is removed.
</li>
<li>
Second check is now also in IRAPI, urls with different status  code than 200 are filtered, and marked for deletion.
</li>
<li>
But it is "neverending" story as I see, there are still special cases, that are not generally recognizable - for example avro responses with <i>"Der gewünschte Beitrag ist nicht mehr verfügbar."</i> and status code 200. 
</li>
<li>
This cases cleanup is not implemented yet. I plan basic implementation for this week.
</li>
<li>
However, an accuracy will never be 100%, especialy when the whitelist can change and pages from whitelist are changing too.  To catch all cases can be done incrementaly, when bug is discovered.
</li>
</ul>

Here is testing:
![accuray_working_urls](https://cloud.githubusercontent.com/assets/2403914/5338513/3d48adce-7ed5-11e4-8071-628334cdf117.jpg)

**Comment by rtroncy** [comment] 2014-12-08 14:38
Thanks for this follow-up. I agree, this is a "never-ending" story and indeed, there is not much you can do for sites that return you a 200 OK but a message telling you that the resource is no longer available for whatever reason.

Just to understand your test: you submit those 5 queries to IRAPI for each media type, you count the number of results returned by IRAPI. They ALL have a 200 OK  code. You manually? verify those links and for most of them you could access the resource. Correct?

**Comment by cervebar** [comment] 2014-12-08 16:01
Yes, thats what I did. I just limit number of returned rows.

**Comment by rtroncy** [comment] 2014-12-08 21:57
Thanks. This closes this issue. Now, please, let's work on issue #4. What is the status?

**Closed as completed by rtroncy** 2014-12-08 21:57 UTC
