### ISSUE TITLE
UEP/EURECOM harmonize on queries for multiple entities

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#13] opened 2014-07-24 11:09 UTC
" In a nutshell, there are many (search) services under
MediaCollector and they have a different behavior when multiple terms is
used in the query. We have start to work on harmonizing this, having a
more complex logic in MediaCollector and this is unfinished. What I
noticed is that we also have a bug in the sense that what is submitted
to MediaCollector for the white list does not return exactly what the
UEP Structured Search API returns. This is dues to the way of how the
query is formulated, in particular how to interpret multiple terms. We
will work on this in the coming days, we need also more support from UEP." (Raphael, 24 July)

**Comment by kliegr** [comment] 2014-07-28 12:22
Lyndon, can I close this as a duplicate of #14?

**Comment by rtroncy** [comment] 2014-07-28 12:28
No, this is not the same bug.
- #14 is about the (human friendly) label of the source being crawled by the UEP module.
- #13 is about how to better integrate the UEP module with MediaCollector/TVEnricher when multiple entities (strings actually) are used in the query

**Comment by kliegr** [comment] 2014-08-05 08:43
In the new release (in beta) we have improved on how multiple entities in a  query are handled. Currently, if three entities  (keywords) are in the query, all of them have to be found in the document for it to be marked as  relevant. This is why the following query from WP5 Scenario realisation returns empty result set:
http://ir.lmcloud.vse.cz/irapi/media-server/?q=Spargel+Brandenburg+K%C3%A4lte&media_type=video&row=10&thd=yes&domain_source=RBB
(even if &searchAll=true is appended)

In the new release, a relevant document does not have to match in all keywords, however  match in multiple keywords increases the relevancy.
http://ir-dev.lmcloud.vse.cz/irapi/media-server2/?q=Spargel+Brandenburg+K%C3%A4lte&media_type=video&row=10&thd=yes&domain_source=RBB
This returns multiple documents, where the first one actually contains two of the keywords.

(&searchAll=true is deprecated in the new release)

**Comment by rtroncy** [comment] 2014-08-05 08:48
Great! How do we get this feeling of different relevancy among the documents returned? There is not confidence (relevance) score associated with the results. The order seems crucially important, right?

**Comment by lyndonnixon** [comment] 2014-08-05 12:57
This is a good step in the right direction!

I agree with @rtroncy  that we need some relevancy score, or (for me at least) even just a field which indicates which of the 1-3 entities was matched for that document.

Note my feeling at http://www.linkedtv.eu/wiki/index.php/RBB_video_enrichment_process#Ranking_of_entities_and_organisation_of_linksets that the combination of entities is important for enrichment in the news scenario. There is a difference between core entities that have to be matched and contextual entities which simply qualfy a matching story as more relevant: the news item about the late asparagus harvest in Brandenburg due to the cold weather had "asparagus" as an entity that had to be matched (I didnt feel a story about cold weather in Brandenburg in general makes a good enrichment in this context). Michiel has also been talking about determining entity importance. 

I'm not clear on how many entities are returned by NamedEntityExpander for every news item but THREE does seem to me to be a reasonable number for the subsequent enrichment (e.g. 1 core + 2 contextual)

**Comment by rtroncy** [comment] 2014-08-05 13:32
Per minutes of today's telecon, there will be a new experimental field called "relevance" added in the enrichment results for which the value will be numerical and in the range [0,1]. Hence, enrichments will be ranked.

This is not yet what you call entity relevance. The Expansion service is described at http://www.linkedtv.eu/wiki/index.php/EntityExpansion. It typically expands an initial set of entities from a program / chapter (10 entities) into a much larger set where entities are ranked so you can threshold where ever you want.

**Comment by lyndonnixon** [comment] 2014-08-18 09:21
As an additional comment on this, I didnt see any indication in the TVEnricher documentation how multiple entities are handled in a query, e.g. qould q=Nelleke+van+der+Krogt be parsed as a single string or as four separate strings. @jluisred

**Comment by lyndonnixon** [comment] 2014-08-18 12:16
Quick test on this revealed again still issues about how this is working (http://www.linkedtv.eu/wiki/index.php/RBB_video_enrichment_process#Automatic_Enrichment)

Instead of matching on title and description (again, RBB has this explicitly in the metadata of its HTML pages) you match on any text extracted from the webpage, so any search with "Brandenburg" for example gets lots of irrelevant results since you seem to match on "Rundfunk Berlin Brandenburg" as station name on any of its video pages!

Reducing to just Spargel, the number of matches is still extremely low compared to how many videos there are in RBB white list sites with Spargel in their title.(see http://www.linkedtv.eu/wiki/index.php/RBB_video_enrichment_process#Curated_Enrichment)

Searching on other entity combinations was disastrious, Spargel AND Saison returned endless pages from arte.tv matching the French word for TV season, Spargel AND Ernte or Spargel AND Frühling failed to return anything more specific than the earlier results for Spargel alone. Compare this to my Google CSE (set up in less than 30 minutes) which found specific videos in the ARD Mediathek (http://www.linkedtv.eu/wiki/index.php/RBB_video_enrichment_process#Comparison_to_use_of_a_Google_CSE)

**Comment by rtroncy** [comment] 2014-08-19 10:04
@lyndonnixon TVEnricher documentation well describes what can be done at the moment in terms of queries. This issue is exactly about discrepancies when queries are conjunctive, and since this issue is not closed, we are still working on it. ETA = later this week

**Comment by rtroncy** [comment] 2014-08-19 10:06
@lyndonnixon Your second comment seems to be a different issue, i.e. how IRAPI is indexing / responding. If this is the case, please open a proper new issue. This issue is JUST about having the same results when calling IRAPI directly versus via TVEnricher, which, at the moment, is not the case (in particular for conjunctive queries).

**Comment by jluisred** [comment] 2014-08-24 20:12
Solved.  The same query "Nelleke+van+der+krogt" launched on the different services:

IRAPI:
http://ir.lmcloud.vse.cz/irapi/media-server/?q=%22Nelleke+van+der+krogt%22&media_type=video&row=25&thd=no&domain_source=SV

MediaCollector:
http://linkedtv.eurecom.fr/api/mediacollector/search/SV/%22Nelleke+van+der+krogt%22

TVEnricher:
http://linkedtv.eurecom.fr/tvenricher/api/entity/enrichment/SV?q=%22Nelleke%20van%20der%20Krogt%22

... produces the same set of results. 
(Please note that the maximum number of results has been set to 25 and MediaCollector and TVEnricher consider also images)

**Closed as completed by jluisred** 2014-08-24 20:12 UTC
