### ISSUE TITLE
THD: 500 error when processing a long RBB subtitle

### ISSUE THREAD

**Issue by jluisred** [linkedtv/wp2#17] opened 2014-08-07 11:13 UTC
This is a bug related to THD. We are trying to process the [rbb AKTUELL vom 04.04.2013 21:45 Uhr](http://data.linkedtv.eu/mediaresource/cbff5a80-a5b6-11e2-951c-f8bdfd0abfbd) media resource. Either calling THD directly or via NERD returns a  500 Internal Error from your service. In the details:

REST call: 
https://ner.vse.cz/thd/api/v1/hypernyms?lang=de&entity_type=ne&provenance=thd,dbpedia&types_filter=all&knowledge_base=linkedHypernymsDataset&priority_entity_linking=false

THD does not support timed text. We generate a new [txt file](https://dl.dropboxusercontent.com/u/4909358/BERLIN-2013-04-04-21-45-53-04042145.txt) containing only the text of the subtitles without the time information.

As a side note, I have tried with smaller excerpts of the same file and it worked fine. So I suspect it could be something related with either the length of the text to be processed or the presence of German characters.

Background information: trying to run the EntityExpansion module as described in http://www.linkedtv.eu/wiki/index.php/RBB_video_enrichment_process

**Comment by m1ci** [comment] 2014-08-11 08:35
This happens due to the length of the text - it is a very long text and a timeout occurs. Why don't you split and process small excerpts of the input text?

If I am not wrong, NERD does splitting/merging of texts.

**Comment by rtroncy** [comment] 2014-08-12 11:55
You're partially wrong @m1ci. Adding more and more logic to NERD is something we do carefully. In this case, one can split texts when we know precisely: what is the text limit that an extractor can deal with? how the extractor works internally, i.e. how the splitting should be done for not negatively impacting the NER detection. Hence, we will not do the same splitting if an extractor works at the sentence or at the paragraph level, etc. AFAIK, you have NEVER provide such an information. Therefore, we submit a complete text to THD.

As an interim solution, I suggest you become more liberal and accept longer text such as a typical subtitle file for an RBB news program, or a TKK program.

**Comment by m1ci** [comment] 2014-08-14 10:39
Hi, the issue is solved and without problems you can process the long RBB subtitle.

Test request:
curl --insecure -X POST --data-urlencode @BERLIN-2013-04-04-21-45-53-04042145.txt "http://entityclassifier.eu/thd/api/v2/extraction?lang=de&entity_type=all&provenance=thd,dbpedia&types_filter=dbo&knowledge_base=linkedHypernymsDataset&priority_entity_linking=true&apikey=xxxxxxxxxxxxxx&format=json"

Back to the splitting/merging thing, I see two solutions for processing very very long texts:
- 1: merging/splitting from the client side, or
- 2: establishment of asynchronous communication with a client-side polling

**Comment by rtroncy** [comment] 2014-08-14 12:13
Thanks. I will close this issue for now.
If you expect a client to either split text before submitting it to THD or to send streams of text (in a client-side polling), you need to indicate what is the MAX size that THD handles. Do you have this information?

**Closed as completed by rtroncy** 2014-08-14 12:13 UTC
